### ISSUE TITLE
Merge cells horizontally

### ISSUE THREAD

**Issue by yaroslav-gwit** [aquasecurity/table#18]
Hi and thank you for this amazing library. Could you please let me know if there is a way to merge cells horizontally? If not, is there a plan to implement this feature?

**Comment by liamg** [comment]
Hi @yaroslav-gwit  - there's no way to explicitly do this, but you can use the (very experimental) colspans feature to achieve it unless you need to do it dynamically. Example [here](https://github.com/aquasecurity/table/blob/main/_examples/14-header-colspans/main.go).

**Comment by yaroslav-gwit** [comment]
Hi @liamg, thank you for your answer, it perfectly suits my use case, but would be great to see an auto merge feature for the normal cols as well at some point :)
